Feature/profile
ooheunda/node4th-pyeonmechu-web pull request #5
Opened 2024-02-08 05:30 UTC by jaecoder222

프로필 조회, 수정, 탈퇴, 다른사람 포스트 보기 API

2024-02-08 06:05 UTC, ooheunda requested changes
프로필 수정 부분에서, body에 값이 안 들어오는 경우를 고려하여 업데이트를 해야 할 것 같습니다. (클라이언트에서 처리하는 부분일까 싶긴 합니다만!!) 그리고 마지막 상태 코드도 변경 부탁드립니다.
회원 탈퇴 부분도 상태 코드 수정해주세요! Not Found는 다 404입니다.
다른 사람 포스트 보기 잘 하셨는데 110번째 줄에 오타가ㅠㅠ 그리고 그 유저 프로필 데이터도 마지막에 같이 담아서 응답해주세요. 인스타그램 느낌으루다가 아시죠?

2024-02-08 07:46 UTC, ooheunda requested changes
- 유저 라우터 173번째 줄부터
  이 부분은 회원가입이 아닙니다...! 이메일, 이름, 비밀번호는 필수값이 아닙니다. (입력값에 대한 상태코드도 401이 아니라 400입니다ㅠㅠ) 프론트엔드 단에서 콜럼 값이 없을 경우 기존 정보를 담아 요청하는 코드를 작성할 수도 있겠지만, 일단은 저희끼리니까 이 로직 안에서, 유저가 닉네임만 수정하는 경우, aboutMe만 수정하는 경우 등 (이 경우 다른 값은 모두 undefined일텐데 update에 그대로 들어갑니다.) 모든 경우를 고려하는 코드를 추가해주시길 부탁드립니다. 
- 191번째 줄에서 수정 권한을 확인하는 부분은 좋은데, 뭔가... 뭔가...ㅠㅠ 이 부분은 이따가 시간 되실때 말로 설명 해주세여.
- 생성/수정 등 새로운 리소스 생성 시 Status code는 201입니다.
- authMiddleware에서 이미 user가 존재하지 않는 경우에 대한 예외처리를 하고 있어서, 인가 미들웨어를 거치는 API에서의 232번째 줄과 같은 예외 처리는 필요 없을 것 같습니다.
- params 변수명 수정해주세요. 변수명도 이상하고, 저렇게 하면 할당 제대로 안 될 것 같아요.

- 다른 사람 포스트 보기 (남의 프로필 보기)에 인가는 필요 없습니다. userId는 내가 아니라 상대(프로필 볼 대상)의 것이어야 합니다.
- posts를 찾는데 postId가 아니라 userId로 찾아야 합니다. 특정 사용자의 프로필에 들어가 프로필을 보고, 포스트도 같이 뜨는 형식입니다.
- 257번째 줄에 조건문은 왜 사용하셨는지 설명해주세요.
- 260번째 조건문도 설명해주세요...

저녁 시간 전에 재형님 시간 되실때 저 찔러주세요...

2024-02-08 12:21 UTC, ooheunda requested changes
수정 부분
- patch 메서드 특성에 대한 부분 더 찾아보시고 (전 전혀 몰랐음. 죄송합니다) 기본값 설정한 코드들 리팩토링 해주시고, 인가 라우터랑 겹치는 코드들도 적절히 삭제해주세요.

탈퇴 부분
- 리다이렉트 한 번 찾아보시고 추가하면 좋을 것 같아요!

남의 프로필 보기
- 포스트 중복해서 불러오는 부분 리팩토링, 프로필은 한 번만 불러와도 됩니다. 데이터 응답 보낼때 꼭 조인 안하셔도 됨!

2024-02-09 09:38 UTC, ooheunda requested changes
- 게시글 생성에서 title, content 유효성 검사가 테스트할때 잘 뜨던가요?
- 비밀번호 수정시엔 confirm도 받아야 합니다. (과제 페이지 참고)
- 다른 사람 포스트 보기에서, 굳이 포스트가 존재하는지 확인하지 않아도 될 것 같아요, 그냥 빈 배열로 보내거나 db에서 받아오는 코드를 한 번만 써도 가능합니다.

2024-02-09 09:50 UTC, slianzg commented
자기 프로필 수정API
1. email은 수정할 필요없으니 안받아도 될 것 같습니다.
만약 이메일도 수정가능하게 할거면, 회원가입 할 때 처럼 기존에 동일한 이메일을 쓰는 사용자가 있지 않은지 확인하는 로직이라도 필요할 것 같아요.

2. 183-184번줄 이 확인작업이 필요한 로직일지 저도 좀 긴가민가하네요... 
어차피 로그인한 토큰에 기록된 유저의 정보를 불러와서 바꾸는 작업이니까, 
높은확률로 USER일거고... 사용자 인증에서 걸러주니까 user를 못찾을 것 같지는 않아서요...!

3. 혹시 패스워드를 변경하는 작업을 의도하신거면, 
변경하려는 비밀번호를 저장할때 bcrypt로 hash처리된 상태로 넣어야하지 않을까요?

4. 프로필을 수정하려고 할 때, 기존의 패스워드를 확인하는 로직이 있으면 좋을 것 같습니다!

다른 사람 프로필 보기 API
1. otherspost는 뭘 가져오는거고, 왜 가져오는 건가요? 이해가 잘 안됩니다..! 설명이 필요해요...

2024-02-11 07:04 UTC, ooheunda requested changes
테스트 해보신거 맞나요? 모든 예외처리에 대해 테스트 해보셔야 합니다.
- 게시글 생성에서 이미 create한 후 유효성 검사를 하면 무슨 의미가 있죠?
- 수정에서 ExistingPassword가 기존 비밀번호고 password가 바꿀 비밀번호, passwordConfirm이 바꿀 비밀번호에 대한 확인 아닌가요? 이후 비크립트 부분 로직이 이해가 안 되고 유효성 검사도 몇 개 빠진 것 같습니다. 그리고 식별자 네이밍 규칙 지켜주세요. 오타도 났네요.
- 회원 탈퇴 부분 테스트를 안 하셨거나 에러 메세지를 못 보신 것 같네요.

어려운 부분 있으면 혼자서 하지 마시고 팀원에게 질문하면서 풀어나갑시다~ 제가 연휴동안 잘 못 들어와서 연휴 동안엔 어떻게 진행중인지는 잘 모르겠는데, 재형님 소통을 좀 더 하시면 좋겠습니다.

+ 스키마 Users랑 Posts 관계 설정 수정하셨던데, 이 부분 젭 접속하시면 팀원들이랑 얘기해주세요. 서린님께 관련 부분 말씀드려 놓았습니다! 스키마같이 공용으로 사용되는 핵심 파일은 수정하실 때 꼭 상의해주세요.

2024-02-11 17:08 UTC, merged